//nested array list of questions for advanced quiz with 4 multi-choice options and the correct answer
var advQuestions = [
	//1-10
	["What natural phenomena are measured by the 'Richter Scale'?", "Earthquakes", "Hurricanes", "Tornados","Tsunamis","A"],
	["In which country is a 'gamelan orchestra' most commonly found?","China","Malaysia","Indonesia","Japan","C"],
	["What is the capital city of Kenya?","Cairo","Nairobi","Pretoria","Tripoli","B"],
	["What is the line of latitude 23.5 degrees north of the Equator called?","Tropic of Capricorn","Polar Circle","Arctic Circle","Tropic of Cancer","D"],
	["A giraffe's tongue is what colour?","Red","Green","Black","Pink","C"],
	["Lechon is a dish made with which meat?","Beef","Lamb","Bacon","Pork","D"],
	["Great Danes come from what European country?","Finland","Austria","Denmark","Germany","D"],
	["Anna Gordy was the first wife of which late soul singer?","Sam Cooke","Luther Vandross","Teddy Pendergrass","Marvin Gaye","D"],
	["In the human body, where is the humerus bone?","Lower Leg","Upper Leg","Lower Arm","Upper Arm","D"],
	["What common salad ingredient belongs to the aster family?","Lettuce","Tomato","Onion","Cucumber","A"],
	
	//11-20
	["Who was the first ever US president to resign in office?","Ronald Reagan","Richard Nixon","Jimmy Carter","Franklin Roosevelt","B"],
	["Piemont and Lombardy are regions in which European country?","France","Spain","Italy","Belgium","C"],
	["In which year was Joan of Arc burnt at the stake?","1431","1450","1500","1561","A"],
	["Golf was first played in which country?","Scotland","France","England","Ireland","A"],
	["Who directed the movie 'Alien'?","Tim Burton","Steven Spielberg","Ridley Scott","Quentin Tarantino","C"],
	["What is the square root of 196?","12","13","14","15","C"],
	["Former French President Charles de Gaulle said 'How can you govern a country which has 24 varieties of...' what ?","Bread","Wine","Cheese","Grapes","C"],
	["Rodgers and Hammerstein named what musical after a US state?","Georgia","Texas","Iowa","Oklahoma","D"],
	["Which element does 'K' represent on the Periodic Table?","Magnesium","Calcium","Potassium","Radium","C"],
	["Which country was formerly known as Gaul?","Spain","France","Italy","Greece","B"],
	
	//21-30
	["Which US state has the longest coastline?","Alaska","California","Florida","Oregon","A"],
	["A lateral curvature of the spine is called what?","Scoliosis","Hepatosis","Sclerosis","Osteoporosis","A"],
	["How is Brazilian footballer Edison Arantes do Nasciamento better known?","Pelé","Neymar","Kaká","Hulk","A"],
	["Kate Moss became the face of what in 1998?","Max Factor","Maybelline","L'Oreal","Rimmel","C"],
	["The liqueur Maraschino is flavoured with which fruit?","Apples","Cherries","Strawberries","Bananas","B"],
	["Stranger's Gate is an entrance to which famous park?","Hyde Park, London","Central Park, New York","Phoenix Park, Dublin","Griffith Park, Los Angeles","B"],
	["In the human body, what is the more common name for the Tympanum?","Brain","Eyeball","Eardrum","Toe","C"],
	["Which basketball star is kidnapped by cartoon characters in the 1996 film 'Space Jam'?","Shaquille O'Neal","Michael Jordan","Magic Johnson","Charles Barkley","B"],
	["The song 'Food, glorious food' was featured in what musical?","Annie","Oliver","Cats","Charlie and the Chocolate Factory","B"],
	["Which singer joined Mel Gibson in the movie Mad Max:Beyond The Thunderdome?","Tina Turner","Whitney Houston","Diana Ross","Cher","A"],
	
	//31-40
	["What actor had a child named Sage Moonblood?","Kevin Costner","Jon Voight","Robert De Niro","Sylvester Stallone","D"],
	["How many bails are used in a game of cricket?","3","4","5","6","B"],
	["Chernobyl is in what country?","Ukraine","Belgium","Romania","Bulgaria","A"],
	["Which London palace is the official residence of the Archbishop of Canterbury?","Lambeth Palace","Buckingham Palace","Kensington Palace","St. James's Palace","A"],
	["Which of Snow White's seven dwarves wear glasses?","Doc","Dopey","Grumpy","Happy","A"],
	["What was the Teenage Mutant Ninja Turtles favourite food?","Cake","Pizza","Bread","Chocolate","B"],
	["In which Dicken's novel was Miss Havisham jilted on her wedding day?","Oliver Twist","A Christmas Carol","David Copperfield","Great Expectations","D"],
	["The first commercially manufactured breakfast cereal was called what?","Cornflakes","Rice Krispies","Shredded Wheat","Frosties","C"],
	["Which country is the smallest member of UEFA in terms of population?","Cyprus","Malta","Wales","Gibraltar","D"],
	["The main diet of the Koala Bear consists of leaves from which tree?","Bamboo Tree","Eucalyptus Tree","Christmas Tree","Oak Tree","B"],
	
	//41-50
	["In Scotland, what are breeks?","Food","Drinks","Trousers","Breaks","C"],
	["Which animal is depicted on the logo of Peugeot cars?","Sheep","Bull","Horse","Lion","D"],
	["Prunes are dried what?","Nectarines","Apricots","Peaches","Plums","D"],
	["What falling fruit supposedly inspired Isaac Newton to write the laws of gravity?","Orange","Pear","Apple","Banana","C"],
	["The Simpson Desert is on which continent?","Africa","Australia","USA","Europe","B"],
	["What nationality was the composer Chopin?","Polish","Danish","Swiss","Austrian","A"],
	["What are the two moons of Mars?","Phobos and Diemos","Deimos and Triton","Triton and Phobos","Deimos and Oberon","A"],
	["How many lines are in an English sonnet?","12","13","14","15","C"],
	["Where were the 1932 and 1984 Olympic Games held?","Athens","Los Angeles","London","Paris","B"],
	["How many points are there on a compass?","30","32","34","36","B"],
	
	//51-60
	["Which country is known as the George Cross Island?","Cyprus","Malta","Mauritius","Samoa","B"],
	["Mal de mer is the French term for which ailment in humans?","Seasickness","Headache","Toothache","Backache","A"],
	["In which US city did house music originate?","Los Angeles","New York City","Chicago","Detroit","C"],
	["How many eyelids do camels have on each eye?","0","1","2","3","D"],
	["Consumption was the former name of which disease?","Leprosy","Polio","Tuberculosis","Measles","C"],
	["Which of these are sedimentary rock?","Quartzite","Granite","Basalt","Sandstone","D"],
	["A cart called a Sulky is used in which sport?","Lacrosse","Rodeo","Golf","Harness Racing","D"],
	["Roman numeral XCV is what number?","95","150","1050","1095","A"],
	["Which country is Lima the capital of?","Peru","Bolivia","Ecuador","Colombia","A"],
	["What does a funambulist do?","Trampolining","Trapezing","Tightrope Walk","Juggling","C"],
	
	//61-70
	["How many players are on a Gaelic football team (excluding substitutes)?","11","15","16","17","B"],
	["How long is the appointed term of office of the secretary general of the United Nations?","Four Years","Five Years","Six Years","Seven Years","B"],
	["In which country did the Mau Mau uprising (1952-1960) occur?","China","Somalia","Japan","Kenya","D"],
	["What is the term for a person with assets of over 1,000 million dollars?","Billionaire","Millionaire","Trillionaire","","A"],
	["Laura Robson is associated with which sport?","Cycling","Tennis","Swimming","Gymnastics","B"],
	["Who was the first US president to speak in Westminister Hall in London?","Barack Obama","Ronald Reagan","George W. Bush","John F. Kennedy","A"],
	["What is the smallest breed of dog?","Beagle","Pug","Chihuahua","Terrier","C"],
	["What is the instrument used to measure relative humidity called?","Hygrometer","Thermometer","Barometer","Hydrometer","A"],
	["Jerry Cruncher appears in which Charles Dicken's novel?","Hard Times","A Tale of Two Cities","A Christmas Carol","Little Dorrit","B"],
	["What does the N stand for in NATO?","New","Non","Nations","North","D"],
	
	//71-80
	["In American football, where do the Broncos come from?","Seattle","Denver","Chicago","Detroit","B"],
	["What is the symbol in the Periodic Table for Iron?","Ir","Fe","K","Au","B"],
	["The cat Gray-Malkin appears in which Shakespeare play?","King Lear","Macbeth","The Merchant of Venice","Romeo and Juliet","B"],
	["What colour graded slope do expert skiers use?","Green","Black","Orange","Blue","B"],
	["How is Stefani Joanne Angelina Germanotta better known in the music industry?","Fergie","Rihanna","Lady Gaga","Pink","C"],
	["What is Entomology the study of?","Rocks","Insects","Frogs","Lizards","B"],
	["Which country gave the USA the Statue of Liberty?","Denmark","Spain","Italy","France","D"],
	["Which perfume was named after Coco Chanel's birthday?","Chanel No. 3","Chanel No. 5","Chanel No. 22","Chanel No. 19","D"],
	["What's the ballet term for a 360 degree turn on one foot?","Brisé","Coupé","Pirouette","Plié","C"],
	["What is the national bird of India?","Peacock","Nightingale","Golden Eagle","Kiwi","A"],
	
	//81-90
	["What is the title of singer Bruno Mars' debut album released in October 2010?","Unorthodox Jukebox","Doo-Wops and Hooligans","Just The Way You Are","The Lazy Song","B"],
	["How many arms/legs does a starfish usually have?","2","3","4","5","D"],
	["What was the name of the high school in the movie 'Grease'?","John Adams High School","Bayside High School","Rydell High School","North Shore High School","C"],
	["A peregrine is what type of bird?","Eagle","Condor","Falcon","Vulture","C"],
	["Pogonophobia is the fear of what?","Puppets","Cats","Smells","Beards","D"],
	["FILA is an international federation for which sport?","Tennis","Lacrosse","Cricket","Wrestling","D"],
	["The llama belongs to the family of animals commonly called what?","Camels","Zebras","Goats","Sheep","A"],
	["How many lines usually make up a limerick?","2","3","4","5","D"],
	["How many laps is the Indianapolis 500?","50","100","200","500","C"],
	["Which European city is said to be the first to introduce house numbers in 1512?","Paris","Rome","Athens","Madrid","A"],
	
	//91-100
	["By definition, Angora wool comes from the Angora goat or the Angora what?","Alpaca","Deer","Sheep","Rabbit","D"],
	["In the human body, the word dermal refers to what?","Skin","Heart","Liver","Kidneys","A"],
	["Canada has how many provinces?","10","12","14","16","A"],
	["In humans, a hemispherectomy is the removal of half of the what?","Stomach","Heart","Brain","Liver","C"],
	["The Covenant are fictional military alien races in which game series?","Call of Duty","Halo","Battlefield","Warcraft","B"],
	["From what animal do we get cashmere?","Sheep","Goats","Deers","Zebras","B"],
	["Which US city is the setting for the 1987 film 'Robocop'?","Los Angeles","Chicago","Detroit","New York City","C"],
	["The family drama '7th Heaven' launched the acting careers of which of these Hollywood stars?","Jessica Biel","Jessica Lowndes","Jessica Simpson","Jessica Alba","A"],
	["Which Asian city was previously known as Edo?","Beijing","Shanghai","Hong Kong","Tokyo","D"],
	["How is the constellation Ursa Minor better known?","Big Dipper/Plough","Northern Cross","Little Dipper","FishHook","C"],
	
	//101-110
	["In which country is the world's highest waterfall?","Colombia","Venezuela","Brazil","Paraguay","B"],
	["What was the name of Jim Carrey's pet Jack Russell Terrier in the 1994 film The Mask?","Milo","Max","Rusty","Rudolph","A"],
	["What country has the internet domain .fi?","France","Finland","Fiji","Faroe Islands","B"],
	["How many squares are there on a chessboard?","60","62","64","66","C"],
	["Prague is in what country?","Bulgaria","Croatia","Latvia","Czech Republic","D"],
	["What is the main ingredient of borscht soup?","Potato","Tomato","Beetroot","Leek","C"],
	["'Roligans' are football fans from which country?","Switzerland","Romania","Finland","Denmark","D"],
	["What are the irregularly-shaped, sticky, colourless bodies in the blood which make it clot?","Platelets","Plasma","Red Blood Cells","White Blood Cells","A"],
	["Whcih author created the character of Tracy Beaker?","J.K. Rowling","Ethel Smyth","Enid Blyton","Jacqueline Wilson","D"],
	["In ancient Egypt, a cubit was a measure of what?","Length","Weight","Temperature","Height","A"],
	
	//111-120
	["Oscine relates to what type of creatures?","Sheep","Insects","Otters","Birds","D"],
	["The perfume L'Interdit by Givenchy was created in 1957 for which actress?","Audrey Hepburn","Grace Kelly","Marilyn Monroe","Elizabeth Taylor","A"],
	["What is the total number of red blood cells found in a normal human body?","10 billion","50 billion","30 trillion","40 trillion","C"],
	["Viernes is Spanish for which day of the week?","Thursday","Friday","Saturday","Sunday","B"],
	["What is the largest type of shark?","Whale Shark","Great White Shark","Goblin Shark","Bull Shark","A"],
	["Which two European countries are connected by the Brenner Pass?","Switzerland and Austria","Germany and Austria","Italy and Austria","Slovakia and Austria","C"],
	["Who was the last president of the Soviet Union?","Mikhail Gorbachev","Vladimir Lenin","Joseph Stalin","Gennady Yanayev","A"],
	["Which wife of Henry VIII was imprisoned in the Tower of London in May 1536?","Catherine of Aragon","Anne Boleyn","Jane Seymour","Anne of Cleves","B"],
	["Which ship picked up over 700 Titanic survivors in April 1912?","HMHS Britannic","HMS Hawke","The Olympic","RMS Carpathia","D"],
	["What two geometric shapes did Archimedes use to mark his tomb?","Sphere and Ellipsoid","Cylinder and Pyramid","Sphere and Pyramid","Cylinder and Sphere","D"],
	
	//121-130
	["In which athletic event is a heavy metal ball thrown?","Discus","Shot Put","Javelin","Hammer","B"],
	["How many bones are in the human neck?","7","8","9","10","A"],
	["In which European city was Oscar Wilde born?","London","Dublin","Paris","Rome","B"],
	["In the human body, what is the hallux?","Hand","Tongue","Thumb","Big Toe","D"],
	["What type of creature is a pintail?","Duck","Frog","Insect","Bird","A"],
	["Amnesty International was founded in what year?","1940","1945","1952","1961","D"],
	["How many people play in a water polo team?","4","5","6","7","D"],
	["Where would you find the Sea of Tranquility?","Earth","Mars","The Moon","The Sun","C"],
	["Which actor won Oscars for his performances in Kramer vs. Kramer and Rain Man?","Dustin Hoffman","Robert De Niro","Arnold Schwarzenegger","Sylvester Stallone","A"],
	["Marie Antoinette was born in which country?","France","Italy","Austria","Spain","C"],
	
	//131-140
	["Who plays the politician who becomes the boyfriend of Jennifer Lopez in the 2003 film Maid in Manhattan?","Alex O'Loughlin","Jude Law","Ralph Fiennes","Hugh Grant","C"],
	["How many letters are in the Welsh alphabet?","22","24","26","28","D"],
	["Chasselas is a variety of which fruit?","Orange","Apple","Pear","Grape","D"],
	["What type of acid is used in car batteries?","Sulphuric","Hydrochloric","Phosphoric","Nitric","A"],
	["On 30th July 1938, the first issue of which children's comic was published in Britain?","Bunty","The Beezer","The Dandy","The Beano","D"],
	["Pumba is what type of animal in the film 'The Lion King'?","Warthog","Lion","Mandrill","Hyena","A"],
	["Italian companies Ferretti and Azimut manufacture which luxury items?","Cars","Yachts","Planes","Trains","B"],
	["The TWIF is the governing body for which sport?","Water Polo","Tug of War","Wrestling","Gymnastics","B"],
	["How many tentacles does a squid have?","8","9","10","11","C"],
	["Which make of car has the advertising slogan 'Zoom, Zoom'?","Toyota","Opel","Mazda","Skoda","C"],
	
	//141-150
	["The Pyramids of the Sun and the Moon are popular tourist attractions in which country?","Paraguay","Peru","Mexico","Chile","C"],
	["Kabuki, a form of highly stylised song, mime and dance originated in what country?","India","China","New Zealand","Japan","D"],
	["In the book 'The Lion, the Witch and the Wardrobe' what type of creature is Maugrim?","Falcon","Lion","Wolf","Badger","C"],
	["What are the names of the two families in Romeo and Juliet?","Percy and Rebeck","Montague and Capulet","Berkeley and Cranmer","Hastings and Page","B"],
	["On which part of the body would a piece of armour called a brassard be worn?","Arm","Leg","Head","Foot","A"],
	["Relating to weather, cirrus is a type of what?","Wind","Cloud","Tornado","Hurricane","B"],
	["The former penal colony Devil's Island lies in which ocean?","Atlantic Ocean","Pacific Ocean","Indian Ocean","Southern Ocean","A"],
	["Which director won a Special Achievement Oscar for his work on the 1995 Pixar film 'Toy Story'?","Spike Lee","David Lynch","John Lasseter","D. W. Griffith","C"],
	["Ombrophobia is an irrational fear of which weather condition?","Snow","Rain","Wind","Cold","B"],
	["Which company introduced the Betamax video cassette system?","Apple","Sony","Samsung","Philips","B"],
	
	//151-160
	["Donnerstag is German for which day of the week?","Tuesday","Wednesday","Thursday","Friday","C"],
	["'The Weeping Woman' is the work of which artist?","Claude Monet","Leonardo da Vinci","Pablo Picasso","Vincent van Gogh","C"],
	["What is the biggest country by landmass in Africa?","Algeria","Egypt","Sudan","Kenya","A"],
	["Xylography is the art of engraving on which substance?","Marble","Glass","Stone","Wood","D"],
	["The Rosetta stone was used to decipher the hieroglyphics in which country?","Egypt","Greece","Italy","Spain","A"],
	["Caballo is Spanish for which animal?","Horse","Dog","Cow","Sheep","A"],
	["In a single season an acre of grape vines can produce how many bottles of wine?","Around 2,000","Around 4,000","Around 6,000","Around 8,000","B"],
	["How many months of the year end in the letter Y?","3","4","5","6","B"],
	["In what year was Prince Andrew born?","1950","1955","1960","1965","C"],
	["Olympus Mons is the highest mountain on which planet in our solar system?","Jupiter","Mars","Venus","Mercury","B"],
	
	//161-170
	["Which American state is nearest to the former Soviet Union?","Iowa","Oregon","California","Alaska","D"],
	["What is the only letter of the alphabet that doesn't appear in the name of any of the states of America?","X","W","Z","Q","D"],
	["A tridecagon has how many sides?","3","300","13","30","C"],
	["Prior to his death, John F. Kennedy Jr. founded what politically-themed magazine?","Philip","Charles","William","George","D"],
	["What year did Mother Teresa win the Nobel Prize for Peace?","1977","1978","1979","1980","C"],
	["The NASDAQ stock exchange is located in which city?","Washington DC","Los Angeles","London","New York","D"],
	["How many stars are on the national flag of Syria?","0","1","2","3","C"],
	["What is Pakistan's currency?","Ruble","Rupee","Dinar","Peso","B"],
	["What is the capital of Sicily?","Palermo","Cagliari","Palma","Victoria","A"],
	["In which James Bond film does actress Jane Seymour play Solitaire?","Diamonds Are Forever","Goldfinger","Die Another Day","Live And Let Die","D"],
	
	//171-180
	["In the human body, the hormone cortisol is produced by which gland?","Thyroid gland","Adrenal gland","Pineal gland","Parathyroid gland","B"],
	["The European port of Split lies in which body of water?","Adriatic Sea","Mediterranean Sea","Ionian Sea","Tyrrhenian Sea","A"],
	["Seal Point and Blue Point are types of which cat?","Burmese","Persian","Siamese","Siberian","C"],
	["On TV, who did the character Lurch work for?","Addams Family","The Jetsons","The Parkers","Cramer family","A"],
	["'A Spaniard in the Works' is a book written by which member of The Beatles?","Paul McCartney","George Harrison","Ringo Starr","John Lennon","D"],
	["Who played Vicky Pollard's twin sister in the 2006 Comic Relief episode of 'Little Britain'?","Kate Thornton","Patsy Kensit","Dawn French","Kate Moss","D"],
	["In computing, what does HTML stand for?","Hyper Text Markup Language","Hyper Text Machine Language","Hyper Type Markup Language","Hyper Type Machine Language","A"],
	["How many balls are on a snooker table at the beginning of a game?","22","24","26","28","A"],
	["Tupan, Dhol and Snare are all types of which musical instrument?","Harp","Piano","Guitar","Drum","D"],
	["What is the first name of comicbook hero Captain Marvel's twin sister?","Joan","Mary","Catherine","","B"],
	
	//181-190
	["What is the highest rating on an EU energy label?","A****","A***","A**","A*","B"],
	["Who played the title role in the 1996 film 'Michael Collins'?","Colin Farrell","Brendan Gleeson","Liam Neeson","Pierce Brosnan","C"],
	["Mercredi is the French for which day of the week?","Monday","Tuesday","Wednesday","Thursday","C"],
	["What did Sergey Brin and Larry Page create?","Twitter","Google","Facebook","Yahoo","B"],
	["Which cartoon character has a rubber chicken called Stretch?","Charlie Brown","Spongebob Squarepants","Popeye","Garfield","D"],
	["In the 2012 Pixar film Brave, eating magic cake turns Merida's mum into what?","A dragon","A frog","A witch","A bear","D"],
	["Which two oceans does the Panama Canal link?","Atlantic and Southern","Atlantic and Pacific","Pacific and Indian","Pacific and Southern","B"],
	["Which US President was in office during the Cuban Missile Crisis?","John F. Kennedy","Lyndon Johnson","Harry Truman","Richard Nixon","A"],
	["In the human body, which vitamin helps the blood to clot?","Vitamin C","Vitamin K","Vitamin D","Vitamin B","B"],
	["The office of the UN General Assembly is in what city?","Paris","London","Brussels","New York City","D"],
	
	//191-200
	["The ringgit is the basic monetary unit of which Asian country?","Japan","Malaysia","Vietnam","South Korea","B"],
	["What word was the Oxford English Dictionary's 'Word of the Year' in 2013?","Selfie","Emoji","Twerk","Bitcoin","A"],
	["Xanthic relates to what colour?","Blue","Green","Yellow","Red","C"],
	["How many wives did English monarch Edward I have?","3","1","0","2","D"],
	["According to the bible, Jesus was baptised in which river?","River Jordan","River Nile","River Euphrates","River Tigris","A"],
	["When did Steve Jobs co-found Apple?","1972","1974","1976","1978","C"],
	["How many books make up the Chronicles of Narnia by CS Lewis?","7","8","9","10","A"],
	["What do the interior angles of a square add up to in degrees?","180","360","270","90","B"],
	["The 2016 Summer Olympics will be held in which country?","France","Japan","Brazil","South Korea","C"],
	["In which battle of 1314 did Robert the Bruce defeat the English forces?","Yeavering","Newburn","Bannockburn","Alnwick","C"]
];