////nested array list of questions for beginner quiz with 3 multi-choice options and the correct answer
var begQuestions = [
	//1-10
	["What is the capital of Spain?", "Barcelona", "Madrid", "Valencia", "B"],
	["What is the surname of the singer Rihanna born on February 20, 1988?","Moore","Ferguson","Fenty","C"],
	["How many dots are there in total on a pair of dice?","42","44","48","A"],
	["How is the number 5 written in Roman Numerals?","X","M","V","C"],
	["What year did Elvis Presley die?","1977","1978","1979","A"],
	["Where does Homer Simpson work?","The Frying Dutchman","Nuclear Power Plant","Moe's Tavern",,"B"],
	["The Book of Kells was written in what language?","English","Irish","Latin","C"],
	["In what country is Qantas the national airline?","New Zealand","Australia","Indonesia","B"],
	["If it is 4.30p.m. in Dublin in February, what time is it in Los Angeles?","11.30p.m.","6.30a.m.","8.30a.m.","C"],
	["What is the perfect score in a single game of Ten Pin Bowling?","300","400","500","A"],
	
	//11-20
	["How many balls are used in a game of Pool?","14","15","16","C"],
	["Who was the first man on the moon?","Neil Armstrong","Edwin 'Buzz' Aldrin","Michael Collins","A"],
	["Which country owns the Canary Islands?","United Kingdom","Spain","France","B"],
	["What everyday household appliance did John Logi Baird invent in 1926?","Radio","Television","Toaster","B"],
	["In June 1991, the first Sonic the Hedgehog game was published by which video game company?","EA","Nintendo","Sega","C"],
	["Which team has won the UEFA Champions League the most times?","Real Madrid","Manchester United","Bayern Munich","A"],
	["Whose 2013 world tour was called 'The Mrs Carter Show'?","Beyonce","Demi Lovato","Nicki Minaj","A"],
	["What is the name of Mario's brother in the Super Mario games?","Luigi","Spaghetti","Bowser","A"],
	["A couple celebrating their crystal wedding anniversary have been married for how many years?","10","15","20","B"],
	["Which Youtube video was the first to break the record for being viewed 2 billion times?","Psy - Gangnam Style","Justin Bieber - Baby","Miley Cyrus - Wrecking Ball","A"],
	
	//21-30
	["Which of these celebrities is not a twin?","James Phelps","Ashton Kutcher","Jessica Alba","C"],
	["Who wrote Charlie And The Chocolate Factory?","Harper Lee","Roald Dahl","J.K Rowling","B"],
	["Normally the Commonwealth Games are held at intervals of?","4 years","10 years","5 years","A"],
	["Which country is also known as 'The Land Of The Rising Sun'?","Australia","India","Japan","C"],
	["A portrait that comically exaggerates a person's physical traits is called a what?","Caricature","Comic","Photograph","A"],
	["What does 'A' stand for on the scoreboard in a game of tennis?","Awesome","Advantage","Average","B"],
	["Known for his reckless spending, which movie star once paid $276,000 for a dinosaur skull?","Charlie Sheen","Nicholas Cage","Naomi Campbell","B"],
	["In computing, what does the abbreviation 'WWW' stand for?","World Wide Web","Who What When","Wide World Web","A"],
	["How many X chromosomes do women have?","1","2","5","B"],
	["What is the first name of Michael Schumacher's racing car driver brother?","Ralf","Rolf","Joachim","A"],
	
	//31-40
	["What is Iron Man's real name?","Peter Parker","Tony Stark","Nick Fury","B"],
	["With which sport is the Jules Rimet trophy associated?","Rugby","Tennis","Football","C"],
	["Which of the Great Lakes is missing from the following: Michigan, Ontario, Erie and Huron?","Victoria","Como","Superior","C"],
	["Who is the lead singer of the British rock group The Arctic Monkeys?","Alex Turner","Gerard Way","Anthony Keidis","A"],
	["What is the third major Balearic Island with Majorca and Minorca?","Ibiza","Gran Canaria","Tenerife","A"],
	["Which dinosaur has a name that means 'three horned face'?","Triceratops","T-Rex","Velociraptor","A"],
	["How many feet are there in a fathom?","10","6","100","B"],
	["What is the alternative common name for a Black Leopard?","Tiger","Panther","Puma","B"],
	["In which US state would you find Daytona Beach?","Hawaii","Florida","New York","B"],
	["Who played Catwoman in the 1992 film 'Batman Returns'?","Halle Berry","Michelle Pfeiffer","Emma Stone","B"],
	
	//41-50
	["Which month of the year are US presidential elections held?","June","July","November","C"],
	["Who had a hit in 1993 with the song 'I Have Nothing?","Whitney Houston","Mary J Blige","Mariah Carey","A"],
	["In what city would you find people studying art and design at the Fashion Institute of Technology?","New York","London","Paris","A"],
	["What is the policeman's name in the Noddy stories?","PC Plum","PC Peter","PC Plod","C"],
	["Which country was the first ever winner of the FIFA World Cup?","Germany","Uruguay","Italy","B"],
	["A silverback is what type of animal?","Giraffe","Gorilla","Snake","B"],
	["Where would you typically find a stenographer?","Hospital","Fire Station","Courtroom","C"],
	["In American football, how many points is a touchdown worth?","10","6","5","B"],
	["What colour is a ruby?","Green","Blue","Red","C"],
	["What is the main ingredient of the Middle Eastern dish hummus?","Chickpeas","Beans","Lentils","A"],
	
	//51-60
	["Where in your body is your patella?","Mouth","Torso","Knee","C"],
	["As of November 2014, which footballer holds the record for scoring the most UEFA Champions League goals?","Christiano Ronaldo","David Beckham","Lionel Messi","C"],
	["In 2014, Manchester United signed Falcao on loan from which club?","Barcelona","Monaco","Real Madrid","B"],
	["With which girl group did Beyonce first find fame?","Sugababes","Destiny's Child","Misteeq","B"],
	["For which 2012 film did Daniel Day-Lewis win his third Academy Award for Best Actor?","My Left Foot","Lincoln","There Will Be Blood","B"],
	["Who painted the ceiling of the Sistine Chapel?","Michelangelo","Leonardo DaVinci","Claude Monet","A"],
	["Who sailed in the Nina, Pinta and Santa Maria?","Ferdinand Magellan","‎Vasco da Gama","Christopher Columbus","C"],
	["In golf, what is one stroke over par called?","Love","Bogey","Birdie","B"],
	["What is the name of Kim Kardashian and Kanye West's daughter?","Blue","South","North","C"],
	["What Tarantino movie won the 'Best Picture' or prestigious Palme d'Or at the Cannes Film Festival in 1994?","Resevoir Dogs","Inglorious Basterds","Pulp Fiction","C"],
	
	//61-70
	["When Amazon.com first appeared online, what did it only sell?","Shoes","Books","Clothes","B"],
	["Insurgents of what nation took part in the Easter Rising of 1916?","England","Ireland","France","B"],
	["What is the name of Dennis the Menace's dog?","Gnasher","Dancer","Prancer","A"],
	["What is an infant whale called?","Pup","Foal","Calf","C"],
	["Which physical activity involves basket tosses, scorpions, toe-crunches and pyramids?","Cheerleading","Yoga","Parkour","A"],
	["According to legend, in what country are you most likely to meet a leprechaun?","England","Germany","Ireland","C"],
	["What fictional character claims to be 'smarter than the average bear'?","Winnie the Pooh","Paddington Bear","Yogi Bear","C"],
	["In what year did the Apple iPhone become available?","2007","2008","2006","A"],
	["Which Californian born singer released her perfume 'Killer Queen' in August 2013?","Gwen Stefani","Katy Perry","Fergie","B"],
	["Whose nose grew when he told a lie?","Pinocchio","Gepetto","Peter Pan","A"],
	
	//71-80
	["What is the fifth planet from the sun?","Mercury","Uranus","Jupiter","C"],
	["How many stars are there on the American flag?","48","50","52","B"],
	["What was supposedly the profession of Sweeney Todd in London?","Doctor","Dentist","Barber","C"],
	["In which bay is Alcatraz?","Santa Monica Bay","San Francisco Bay","Monterey Bay","B"],
	["What is the name of the host of the UK TV show 'Celebrity Juice?","Keith Lemon","Russell Brand","James Corden","A"],
	["In July 2013, who became the 100th winner of the Tour de France?","Cadel Evans","Bradley Wiggins","Chris Froome","C"],
	["An airplane's black box is usually what colour?","Black","Green","Orange","C"],
	["On what date is US Independence Day?","September 7th","November 26th","July 4th","C"],
	["What colour is Marge Simpson's hair?","Blue","Yellow","Orange","A"],
	["How many carats is pure gold?","20","22","24","C"],
	
	//81-90
	["What was Cinderella's carriage before it was changed by the Fairy Godmother?","Pear","Pumpkin","Apple","B"],
	["How many kilograms make up a metric tonne?","10","100","1000","C"],
	["Which company produces the footballs for the World Cup?","Le Coq Sportif","Nike","Adidas","C"],
	["In the film 'The Mask', which actress starred alongside Jim Carrey?","Cameron Diaz","Drew Barrymore","Lucy Liu","A"],
	["Harry Redknapp is associated with which sport?","Cricket","Rugby","Football","C"],
	["What is a joule the unit of?","Energy","Temperature","Sound","A"],
	["In which Rocky film did Mr T appear as Clubber Lang?","Rocky 1","Rocky 3","Rocky 2","B"],
	["How many events make up a pentathlon?","5","10","15","A"],
	["Which of these animals shares its name with a luxury car?","Jaguar","Puma","Panther","A"],
	["Ancient Egyptian Cleopatra was said to have been killed by which type of snake?","Cobra","Asp","Viper","B"],
	
	//91-100
	["In art, what are the three primary colours?","Red, Yellow, Orange","Red, Green, Blue","Red, Yellow, Blue","C"],
	["What is the art of cutting shrubs into ornamental shapes called?","Aviary","Topiary","Shrubbery","B"],
	["In which city was Martin Luther King assassinated in 1968?","Portland, Oregon","Memphis, Tennessee","Nashville, Tennessee","B"],
	["What is the boiling point of water in degrees Celsius?","100","1000","10000","A"],
	["What car company makes Mustang cars?","Renault","Ford","Bentley","B"],
	["In US currency, how many nickels make a dollar?","5","10","20","C"],
	["Where are the headquarters of FIFA?","London, England","Zurich, Switzerland","Brussels, Belgium","B"],
	["Shaggy, Velma, Fred and Daphne are all characters from which cartoon series?","Ed, Edd & Eddy","Scooby-Doo","Dexter's Laboratory","B"],
	["What is produced by the bacterial fermentation of milk?","Yoghurt","Butter","Cheese","A"],
	["Who directed the Indiana Jones series of films?","George Lucas","Quentin Tarantino","Steven Spielberg","C"],
	
	//101-110
	["The 2009 film 'The Hangover' is set in which city?","Las Vegas","Bangkok","New York","A"],
	["What does the ozone layer restrict?","Infrared Radiation","Ultraviolet Radiation","Gamma Rays","B"],
	["Who did actress Marilyn Monroe marry in January 1954?","Joe DiMaggio","John F Kennedy","Arthur Miller","A"],
	["If a business is 'filing under Chapter 11' what is it doing?","Declaring Bankruptcy","Expanding","Merging with another company","A"],
	["The element hydrogen has which number on the Periodic Table?","5","1","7","B"],
	["What does ROM in CDROM stand for?","Read Only Memory","Real Original Music","Raw Original Memory","A"],
	["The film, The Hunt For Red October was based on the novel of which writer?","Tom Clancy","J.R.R Tolkien","George R.R Martin","A"],
	["How many teams compete in the Barclays Premier League?","30","20","10","B"],
	["How many timezones does Russia have?","3","1","9","C"],
	["Grand Central Terminal in New York is the world's...?","largest railway station","longest railway station","highest railway station","A"],
	
	//111-120
	["What was the first team sport to be included in the Olympic Games?","Football","Volleyball","Basketball","A"],
	["In 1872, which country played England in the first ever international game of football?","France","England","Scotland","C"],
	["Which is the largest borough in New York City?","Manhattan","Queens","The Bronx","B"],
	["How many ribs does a human have?","24","10","6","A"],
	["Who was the 40th President of the United States of America?","John F Kennedy","Barack Obama","Ronald Reagan","C"],
	["If cats are feline, what are sheep?","Ovine","Bovine","Oscine","A"],
	["Bell, Tipi and Chum are all types of what?","Ball","Food","Tent","C"],
	["From what language does the term 'R.S.V.P.' originate?","German","French","Latin","B"],
	["Which planet in our solar system is known as 'The Blue Planet'?","Earth","Pluto","Neptune","A"],
	["What was Gotye and Kimbra's 2013 Grammy Award winning Best Song?","We Are Young","Somebody That I Used To Know","Somebody To Love","B"],
	
	//121-130
	["Who played Joey in the TV show 'Friends?","David Schwimmer","Matthew Perry","Matt Le Blanc","C"],
	["Which sport features line-outs, scrums and conversions?","Football","Rugby","Tennis","B"],
	["Who sang the title song for the 2002 James Bond film 'Die Another Day'?","Adele","Shirley Bassey","Madonna","C"],
	["What number is Hurricane on the Beaufort Scale?","12","11","10","A"],
	["Which 2009 animated film features a floating house suspended by helium balloons?","Frozen","Brave","Up","C"],
	["What is the last letter of the Greek alphabet?","Alpha","Omega","Gamma","B"],
	["Which of the following foods is the best source of protein?","Lettuce","Milk","Fish","C"],
	["The mainland portion of which country is formed by Jutland?","Finland","Denmark","Sweden","B"],
	["What is the name of the family's pet goldfish in the US television series 'American Dad'?","Mila Kunis","Fred","Klaus Heissler","C"],
	["The Golden Gate Bridge is in which US city?","San Francisco","New York","Boston","A"],
	
	//131-140
	["What name is given to a female swan?","Swen","Len","Pen","C"],
	["Which fictional superhero goes by the name of Bruce Wayne?","Superman","Batman","Captain America","B"],
	["In Roman Numerals, how many players are there on a soccer team (excluding substitutes)?","XI","XX","IX","A"],
	["In a game with no wild cards, what is the highest possible poker hand?","Royal Flush","Four of a Kind","Straight Flush","A"],
	["In what year was Margaret Thatcher first elected Prime Minister?","1980","1979","1976","B"],
	["Pug, Boxer and Chow are all breeds of which animal?","Cat","Cow","Dog","C"],
	["What beer is marketed as The King of Beers?","Heineken","Budweiser","Corona","B"],
	["In business terms, what does IMF stand for?","International Money Fund","International Monetary Fund","International Money Foundation","B"],
	["How many years did Nelson Mandela spend in prison?","27","12","30","A"],
	["Blinky, Pinky, Inky and Clyde are the enemies of which game character?","Pac-Man","Tetris","Super Mario","A"],
	
	//141-150
	["Which country singer was known as 'The Man In Black'?","Bruce Springsteen","Johnny Cash","Elvis","B"],
	["According to 2014 Twitter statistics, how many million tweets are sent every day?","250","100","500","C"],
	["What type of animal is Baloo in the novel 'The Jungle Book' by Rudyard Kipling?","Cow","Horse","Bear","C"],
	["Which celebrity couple have children named Apple and Moses?","Jay Z and Beyonce","Keith Urban and Nicole Kidman","Chris Martin and Gwyneth Paltrow","C"],
	["In May 1940, who became British Prime Minister after the resignation of Neville Chamberlain?","Winston Churchill","Margaret Thatcher","Tony Blair","A"],
	["What is the most widely recognised national symbol of Canada?","Maple Leaf","Maple Syrup","Moose","A"],
	["Which of these senses deteriorates first with age?","Sight","Smell","Touch","B"],
	["Which child actor appeared in the video for Michael Jackson's 1991 hit song 'Black or White'?","Corey feldman","Cole Sprouse","Macaulay Culkin","C"],
	["What oath is sworn by graduates of medicine?","Ironclad Oath","Oath of Allegiance","Hippocratic Oath","C"],
	["'Vorsprung durch Technik' is the slogan of which car manufacturer?","Audi","Volkswagen","Opel","A"],
	
	//151-160
	["What is the most populous country in the world?","China","Russia","India","A"],
	["What is the common name for Aurora Borealis?","Christmas Lights","Northern Lights","Southern Lights","B"],
	["Which rock group provided the soundtrack for the film 'Flash Gordon'?","AC/DC","Queen","Led Zeppelin","B"],
	["What is the largest mammal in the world?","Killer Whale","African Elephant","Blue Whale","C"],
	["England's national rugby union side play their home games at which ground?","Twickenham","Lansdowne Road","Murrayfield","A"],
	["The teddy bear was named after which famous person?","Theodore Roosevelt","Teddy Sears","Teddy Geiger","A"],
	["Who has won the most Oscars?","Audrey Hepburn","Walt Disney","Tatum O'Neal","B"],
	["Including the bottom, how many sides does a pyramid have?","3","5","4","B"],
	["Internet is the short form of which technical term?","International","Intranetwork","Internetwork","C"],
	["What is the square root of 16?","4","2","8","A"],
	
	//161-170
	["Which world surfing venue has the biggest waves?","Hawaii","California","Ireland","A"],
	["What is another name for Wildebeest?","Pumba","Bison","Gnu","C"],
	["What beverage is sold with the marketing slogan 'it gives you wings'?","Pepsi","Red Bull","Coca-Cola","B"],
	["What nationality is Usain Bolt?","African","American","Jamaican","C"],
	["In Star Trek, what is the colour of Mr. Spock's blood?","Green","Red","Black","A"],
	["Which male artist won the most awards at the 2014 Billboard Music Awards?","Justin Bieber","Justin Timberlake","Jay Z","B"],
	["Anime is film animation originating in which country?","China","Thailand","Japan","C"],
	["What is the term given to a word that can be spelt the same both backwards and forwards?","Alliteration","Palindrome","Hyperbole","B"],
	["Which country has the internet domain '.fr'?","France","Finland","Switzerland","A"],
	["Malfunctioning of which of the following organs causes jaundice?","Kidneys","Liver","Lungs","B"],
	
	//171-180
	["Hermit, Spider and Blue are all types of what?","Lobster","Crab","Frog","B"],
	["'Red Vineyard at Arles' is believed to be the only painting sold by what artist during his lifetime?","Vincent Van Gogh","Pablo Picasso","Leonard da Vinci","A"],
	["Which reggae singing star died 11th May 1981?","Jimi Hendrix","Bob Marley","Kurt Cobain","B"],
	["What children's story book character believes that the sky is falling?","Peter Pan","Chicken Little","Baloo","B"],
	["Texas Hold 'Em is a variation of which card game?","Bridge","Snap","Poker","C"],
	["Which famous actor has a wife called Jada and children Jaden and Willow?","Samuel L Jackson","Will Smith","Morgan Freeman","B"],
	["Which girls name featured in a Michael Jackson song in 1983?","Mary","Joan","Jean","C"],
	["In which US TV series did Kiefer Sutherland play Jack Bauer?","24","The Wire","The Blacklist","A"],
	["What colour are the Fields in the 1993 single by Sting?","Yellow","Silver","Gold","C"],
	["If you work as a 'dolly grip', what business are you in?","Marketing","Golf","Film Production","C"],
	
	//181-190
	["What colour would Coca Cola be if you were to remove the artificial colouring?","Black","Red","Green","C"],
	["What is the first name of the butler in the US TV series The Fresh Prince of Bel Air?","Geoffrey","Carlton","Will","A"],
	["In mathematics, what is an angle called which measures more than 90 degrees but less than 180 degrees?","Acute","Obtuse","Right","B"],
	["Which children's classic book was written by Anna Sewell?","Black Beauty","The Secret Garden","The Little Princess","A"],
	["If it is 4p.m. in Dublin in February, what time is it in New York City?","9a.m.","10a.m.","11a.m.","C"],
	["The Mona Lisa was painted by which artist?","Michelangelo","Leonardo da Vinci","Donatello","B"],
	["Elephant tusks are made of what material?","Ivory","Calcium","Bone","A"],
	["Which US actor has children named Rumer, Scout and Tallulah?","Bruce Willis","Sylvester Stallone","Robert de Niro","A"],
	["How many pieces does each player begin with in a game of Chess?","14","16","18","B"],
	["What type of food is gelato?","Cake","Ice Cream","Pizza","B"],
	
	//191-200
	["Which prime number is between 11 and 17?","14","15","13","C"],
	["Which large animal kills more people than any other animal in Africa?","Hippopotamus","Giraffe","Hyena","A"],
	["A lucky clover is supposed to have how many leaves?","4","3","5","A"],
	["What exercise apparatus is used during a 'spinning' class?","Resistance Bands","Ball","Stationary Bicycle","C"],
	["In the children's Mr Men books, what shape is Mr Rush?","Rectangular","Square","Triangular","B"],
	["Mycroft is the older brother of which fictional detective?","Hans Solo","Indiana Jones","Sherlock Holmes","C"],
	["Which fast food chain uses the slogan 'I'm Lovin' It'?","Burger King","KFC","McDonald's","C"],
	["Which of these fashion designers was born in the United States?","Donna Karan","Alexander McQueen","Victoria Beckham","A"],
	["What is converted into alcohol during brewing?","Hops","Barley","Sugar","C"],
	["What is the highest range of the female singing voice?","Soprano","Alto","Tenor","A"]
];

